### PR TITLE
Changes from UI discussion today

### LINKED ISSUE #2: Privacy Enhancing datatype
May need to 
- rename the current tool element to tool-category
- add new element for specific tool used, as a String, 0..1

### PR DESCRIPTION
**Pull request by JohnMoehrke**
- Privacy Indicators is renamed to Privacy Enhancing Technologies
- clarify on Concept datatype that when a non-standard concept is used, it typically is done with just the description element 
- Add a tool-used to the Classification datatype, to enable recording of a specific tool used to do the classification Clarify Privacy Enhancing datatype
- Add support in Privacy Enhancing datatype for a specific tool to be indicated as use.
  - close #2 
- Change upper bounds on Privacy Enhancing datatype
- remove from the codes any `-other`, as anything not specific from the code system should be explicitly defined (aka no such thing as -other).

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
These were the items discussed today. One outstanding issue is #3 that we have not yet resolved how to fix or if to fix.

**Comment by kpodnar-dta** [comment]
Thanks @JohnMoehrke. Can you please change Intended Data Use to cardinality 1..* , instead of 0?

**Review by kpodnar-dta — CHANGES_REQUESTED** [review]
Can you please change Intended Data Use to cardinality 1..* , instead of 0?

**Comment by JohnMoehrke** [comment]
changed

**Review by kpodnar-dta — APPROVED** [review]
Great, thanks!

**Pull request merged**
